"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RegisterRequest(google.protobuf.message.Message):
    """Структуры данных (DTO)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    PHONE_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    email: builtins.str
    """Email пользователя (уникальный логин)"""
    first_name: builtins.str
    """Имя пользователя"""
    last_name: builtins.str
    """Фамилия пользователя"""
    phone: builtins.str
    """Номер телефона"""
    password: builtins.str
    """Пароль в открытом виде (хэшируется на сервере)"""
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        first_name: builtins.str = ...,
        last_name: builtins.str = ...,
        phone: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email", "first_name", b"first_name", "last_name", b"last_name", "password", b"password", "phone", b"phone"]) -> None: ...

global___RegisterRequest = RegisterRequest

@typing_extensions.final
class LoginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    email: builtins.str
    """Email пользователя"""
    password: builtins.str
    """Пароль в открытом виде"""
    def __init__(
        self,
        *,
        email: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email", "password", b"password"]) -> None: ...

global___LoginRequest = LoginRequest

@typing_extensions.final
class AuthResponse(google.protobuf.message.Message):
    """Единый ответ для Login и Register"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    token: builtins.str
    """Сгенерированный JWT-токен для авторизации"""
    error: builtins.str
    """Описание ошибки, если авторизация/регистрация не удалась"""
    def __init__(
        self,
        *,
        token: builtins.str = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "token", b"token"]) -> None: ...

global___AuthResponse = AuthResponse

@typing_extensions.final
class ValidateTokenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.str
    """JWT-токен, присланный клиентом в HTTP-заголовке"""
    def __init__(
        self,
        *,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["token", b"token"]) -> None: ...

global___ValidateTokenRequest = ValidateTokenRequest

@typing_extensions.final
class ValidateTokenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_VALID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    is_valid: builtins.bool
    """Статус валидности токена (true/false)"""
    email: builtins.str
    """Email пользователя, извлеченный из токена"""
    error: builtins.str
    """Причина ошибки валидации (например, "Token expired")"""
    role: builtins.str
    """Роль пользователя (например, "ADMIN" или "USER") для RBAC"""
    def __init__(
        self,
        *,
        is_valid: builtins.bool = ...,
        email: builtins.str = ...,
        error: builtins.str = ...,
        role: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email", "error", b"error", "is_valid", b"is_valid", "role", b"role"]) -> None: ...

global___ValidateTokenResponse = ValidateTokenResponse

@typing_extensions.final
class ChangePasswordRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    OLD_PASSWORD_FIELD_NUMBER: builtins.int
    NEW_PASSWORD_FIELD_NUMBER: builtins.int
    token: builtins.str
    """JWT-токен авторизованного пользователя"""
    old_password: builtins.str
    """Текущий пароль (для подтверждения)"""
    new_password: builtins.str
    """Новый пароль"""
    def __init__(
        self,
        *,
        token: builtins.str = ...,
        old_password: builtins.str = ...,
        new_password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["new_password", b"new_password", "old_password", b"old_password", "token", b"token"]) -> None: ...

global___ChangePasswordRequest = ChangePasswordRequest

@typing_extensions.final
class ChangePasswordResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """Статус успешности смены пароля"""
    error: builtins.str
    """Описание ошибки (например, "Неверный старый пароль")"""
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "success", b"success"]) -> None: ...

global___ChangePasswordResponse = ChangePasswordResponse

@typing_extensions.final
class ResetPasswordRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    email: builtins.str
    """Email пользователя, запрашивающего сброс пароля"""
    def __init__(
        self,
        *,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email"]) -> None: ...

global___ResetPasswordRequest = ResetPasswordRequest

@typing_extensions.final
class ResetPasswordResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """Статус успешности отправки пароля"""
    message: builtins.str
    """Информационное сообщение ("Новый пароль отправлен")"""
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> None: ...

global___ResetPasswordResponse = ResetPasswordResponse
