# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nauth.proto\x12\x04\x61uth"h\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t",\n\x0c\x41uthResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t"U\n\x15ValidateTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t"R\n\x15\x43hangePasswordRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x14\n\x0cold_password\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t"8\n\x16\x43hangePasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t"%\n\x14ResetPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t"9\n\x15ResetPasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd6\x02\n\x0b\x41uthService\x12\x35\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x12.auth.AuthResponse\x12/\n\x05Login\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12H\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\x12K\n\x0e\x43hangePassword\x12\x1b.auth.ChangePasswordRequest\x1a\x1c.auth.ChangePasswordResponse\x12H\n\rResetPassword\x12\x1a.auth.ResetPasswordRequest\x1a\x1b.auth.ResetPasswordResponseB-\n\x1e\x63om.school21.shopapi.grpc.authB\tAuthProtoP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "auth_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.school21.shopapi.grpc.authB\tAuthProtoP\001"
    )
    _globals["_REGISTERREQUEST"]._serialized_start = 20
    _globals["_REGISTERREQUEST"]._serialized_end = 124
    _globals["_LOGINREQUEST"]._serialized_start = 126
    _globals["_LOGINREQUEST"]._serialized_end = 173
    _globals["_AUTHRESPONSE"]._serialized_start = 175
    _globals["_AUTHRESPONSE"]._serialized_end = 219
    _globals["_VALIDATETOKENREQUEST"]._serialized_start = 221
    _globals["_VALIDATETOKENREQUEST"]._serialized_end = 258
    _globals["_VALIDATETOKENRESPONSE"]._serialized_start = 260
    _globals["_VALIDATETOKENRESPONSE"]._serialized_end = 345
    _globals["_CHANGEPASSWORDREQUEST"]._serialized_start = 347
    _globals["_CHANGEPASSWORDREQUEST"]._serialized_end = 429
    _globals["_CHANGEPASSWORDRESPONSE"]._serialized_start = 431
    _globals["_CHANGEPASSWORDRESPONSE"]._serialized_end = 487
    _globals["_RESETPASSWORDREQUEST"]._serialized_start = 489
    _globals["_RESETPASSWORDREQUEST"]._serialized_end = 526
    _globals["_RESETPASSWORDRESPONSE"]._serialized_start = 528
    _globals["_RESETPASSWORDRESPONSE"]._serialized_end = 585
    _globals["_AUTHSERVICE"]._serialized_start = 588
    _globals["_AUTHSERVICE"]._serialized_end = 930
# @@protoc_insertion_point(module_scope)
