version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shopapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  shopapi-master:
    build:
      context: ./ShopAPI
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shopapi
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy

  shopapi-replica1:
    build:
      context: ./ShopAPI
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shopapi
      - SPRING_DATASOURCE_USERNAME=readonly_user
      - SPRING_DATASOURCE_PASSWORD=readonly_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      shopapi-master:
        condition: service_started

  shopapi-replica2:
    build:
      context: ./ShopAPI
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shopapi
      - SPRING_DATASOURCE_USERNAME=readonly_user
      - SPRING_DATASOURCE_PASSWORD=readonly_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      shopapi-master:
        condition: service_started

  nginx:
    image: nginx:1.24
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - shopapi-master
      - shopapi-replica1
      - shopapi-replica2
      - pgadmin

      
# --- НОВЫЙ БЛОК: Инфраструктура микросервиса авторизации ---
  
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Пробрасываем наружу на 5433, как на архитектурной схеме
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-api:
    build:
      context: ./AuthAPI
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@auth-db:5432/authdb
      - PYTHONUNBUFFERED=1
    ports:
      - "50051:50051"
    depends_on:
      auth-db:
        condition: service_healthy