syntax = "proto3";

package auth;

// Это настройки для генерации Java-кода

option java_multiple_files = true;
option java_package = "com.school21.shopapi.grpc.auth";
option java_outer_classname = "AuthProto";


// Сервис авторизации 

service AuthService {
    
    // Регистрация нового пользователя
    rpc Register (RegisterRequest) returns (AuthResponse);

    // Вход в систему (Авторизация)
    rpc Login (LoginRequest) returns (AuthResponse);

    // Проверка токена (Валидация при каждом запросе к защищенным ресурсам)
    rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenResponse);

    // Смена пароля (Авторизованный пользователь)
    rpc ChangePassword (ChangePasswordRequest) returns (ChangePasswordResponse);

    // Сброс пароля (Отправка нового пароля при утере)
    rpc ResetPassword (ResetPasswordRequest) returns (ResetPasswordResponse);
}


// Структуры данных (DTO)

message RegisterRequest {
    string email = 1;       // Email пользователя (уникальный логин)
    string first_name = 2;  // Имя пользователя
    string last_name = 3;   // Фамилия пользователя
    string phone = 4;       // Номер телефона
    string password = 5;    // Пароль в открытом виде (хэшируется на сервере)
}

message LoginRequest {
    string email = 1;       // Email пользователя
    string password = 2;    // Пароль в открытом виде
}

// Единый ответ для Login и Register
message AuthResponse {
    string token = 1;       // Сгенерированный JWT-токен для авторизации
    string error = 2;       // Описание ошибки, если авторизация/регистрация не удалась
}

message ValidateTokenRequest {
    string token = 1;       // JWT-токен, присланный клиентом в HTTP-заголовке
}

message ValidateTokenResponse {
    bool is_valid = 1;      // Статус валидности токена (true/false)
    string email = 2;       // Email пользователя, извлеченный из токена
    string error = 3;       // Причина ошибки валидации (например, "Token expired")
    string role = 4;        // Роль пользователя (например, "ADMIN" или "USER") для RBAC
}

message ChangePasswordRequest {
    string token = 1;         // JWT-токен авторизованного пользователя
    string old_password = 2;  // Текущий пароль (для подтверждения)
    string new_password = 3;  // Новый пароль
}

message ChangePasswordResponse {
    bool success = 1;         // Статус успешности смены пароля
    string error = 2;         // Описание ошибки (например, "Неверный старый пароль")
}

message ResetPasswordRequest {
    string email = 1;         // Email пользователя, запрашивающего сброс пароля
}

message ResetPasswordResponse {
    bool success = 1;         // Статус успешности отправки пароля
    string message = 2;       // Информационное сообщение ("Новый пароль отправлен")
}
